# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# PASO DE DIAGNÓSTICO COMPLETO
- script: |
    echo "=== DIAGNÓSTICO INICIADO ==="
    echo "Directorio actual:"
    pwd
    echo ""
    echo "Lista COMPLETA de archivos:"
    ls -la
    echo ""
    echo "Buscando Dockerfile específicamente:"
    find . -name "Dockerfile" -type f
    echo ""
    echo "Contenido del directorio raíz:"
    ls -la /
    echo ""
    echo "Estructura del proyecto:"
    find . -type f | head -30
    echo "=== DIAGNÓSTICO FINALIZADO ==="
  displayName: 'Diagnóstico Completo'

# Solo si encontramos el Dockerfile, continuamos
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
  condition: succeeded()

- script: |
    echo "✅ ¡Build exitoso!"
  displayName: 'Success'